theme = "solarized_dark_jz"

[editor]
bufferline = "always"
color-modes = true
line-number = "relative"

[editor.file-picker]
hidden = false

[editor.whitespace.characters]
tabpad = "·"

[editor.whitespace.render]
tab = "all"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
